FROM node:20-slim
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR '/app'

# Set environment to development
ENV NODE_ENV=development

# Copy package.json and package-lock.json
COPY package.json .
COPY pnpm-lock.yaml .

# Install dependencies using pnpm
RUN pnpm install

# Copy the rest of the app's code
COPY . .

CMD [ "pnpm", "run","start" ]
