version: '3'
services:
  web:
    stdin_open: true # Enable logs
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app                            # Mount the project directory from host
      - /app/node_modules                 # Ensures that node_modules inside the container doesn’t get overwritten by the mounted volume.
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['pnpm', 'run', 'test']
